// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/test": typeof import("./app/routes/test.tsx");
};